---
- name: gather os specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
      - "{{ ansible_distribution|lower }}-{{ ansible_distribution_version|lower|replace('/', '_') }}.yml"
      - "{{ ansible_distribution|lower }}-{{ ansible_distribution_release }}.yml"
      - "{{ ansible_distribution|lower }}-{{ ansible_distribution_major_version|lower|replace('/', '_') }}.yml"
      - "{{ ansible_distribution|lower }}.yml"
      - "{{ ansible_os_family|lower }}.yml"
      - defaults.yml
      paths:
      - ../vars
      skip: true

- name: User | Create User Group
  group: name={{item.group|default(item.name)}} system={{item.system|default(omit)}}
  with_items: "{{ addusers }}"

- name: User | Create User
  user:
    comment: "{{item.comment|default(omit)}}"
    createhome: "{{item.create_home|default(omit)}}"
    group: "{{item.group|default(item.name)}}"
    home: "{{item.home|default(omit)}}"
    name: "{{item.name}}"
    system: "{{item.system|default(omit)}}"
  with_items: "{{ addusers }}"
