---
local_release_dir: /tmp

# Versions
kube_version: v1.2.4
etcd_version: v2.2.5
calico_version: v0.19.0
calico_cni_version: v1.3.0
weave_version: v1.5.0

# Download URL's
kubelet_download_url: "https://storage.googleapis.com/kubernetes-release/release/{{ kube_version }}/bin/linux/amd64/kubelet"
apiserver_download_url: "https://storage.googleapis.com/kubernetes-release/release/{{ kube_version }}/bin/linux/amd64/kube-apiserver"
kubectl_download_url: "https://storage.googleapis.com/kubernetes-release/release/{{ kube_version }}/bin/linux/amd64/kubectl"

etcd_download_url: "https://storage.googleapis.com/kargo/{{etcd_version}}_etcd"
calico_download_url: "https://github.com/projectcalico/calico-containers/releases/download/{{calico_version}}/calicoctl"
calico_cni_download_url: "https://github.com/projectcalico/calico-cni/releases/download/{{calico_cni_version}}/calico"
calico_cni_ipam_download_url: "https://github.com/projectcalico/calico-cni/releases/download/{{calico_cni_version}}/calico-ipam"
weave_download_url: "https://storage.googleapis.com/kargo/{{weave_version}}_weave"

# Checksums
calico_checksum: "6db00c94619e82d878d348c4e1791f8d2f0db59075f6c8e430fefae297c54d96"
calico_cni_checksum: "2f65616cfca7d7b8967a62f179508d30278bcc72cef9d122ce4a5f6689fc6577"
calico_cni_ipam_checksum: "cc362ea55c41b9dfda1e24f4c76da0a4101fa3a6f645fbce2d91d51401f6ba67"
weave_checksum: "28d2c4e2b1ad8600da69882501eba697679aea10a5e61c769aa3a9ee72b0d89a"
etcd_checksum: "aa6037406257d2a1bc48ffa769afe7a4f8a04cc1ffcd36ef84f9ee8bc4eca756"
kubectl_checksum: "dac61fbd506f7a17540feca691cd8a9d9d628d59661eebce788a50511f578897"
kubelet_checksum: "4adaf40592248eef6fd4fa126464915ea41e624a70dc77178089760ed235e341"
kube_apiserver_checksum: "6ac99b36b02968459e026fcfc234207c66064b5e11816b69dd8fc234b2ffec1e"

downloads:
  - name: calico
    dest: calico/bin/calicoctl
    version: "{{calico_version}}"
    sha256: "{{ calico_checksum }}"
    source_url: "{{ calico_download_url }}"
    url: "{{ calico_download_url }}"
    owner: "root"
    mode: "0755"

  - name: calico-cni-plugin
    dest: calico/bin/calico
    version: "{{calico_cni_version}}"
    sha256: "{{ calico_cni_checksum }}"
    source_url: "{{ calico_cni_download_url }}"
    url: "{{ calico_cni_download_url }}"
    owner: "root"
    mode: "0755"

  - name: calico-cni-plugin-ipam
    dest: calico/bin/calico-ipam
    version: "{{calico_cni_version}}"
    sha256: "{{ calico_cni_ipam_checksum }}"
    source_url: "{{ calico_cni_ipam_download_url }}"
    url: "{{ calico_cni_ipam_download_url }}"
    owner: "root"
    mode: "0755"

  - name: weave
    dest: weave/bin/weave
    version: "{{weave_version}}"
    source_url: "{{weave_download_url}}"
    url: "{{weave_download_url}}"
    sha256: "{{ weave_checksum }}"
    owner: "root"
    mode: "0755"

  - name: etcd
    version: "{{etcd_version}}"
    dest: "etcd/etcd-{{ etcd_version }}-linux-amd64.tar.gz"
    sha256: "{{ etcd_checksum }}"
    source_url: "{{ etcd_download_url }}"
    url: "{{ etcd_download_url }}"
    unarchive: true
    owner: "etcd"
    mode: "0755"

  - name: kubernetes-kubelet
    version: "{{kube_version}}"
    dest: kubernetes/bin/kubelet
    sha256: "{{kubelet_checksum}}"
    source_url: "{{ kubelet_download_url }}"
    url: "{{ kubelet_download_url }}"
    owner: "kube"
    mode: "0755"

  - name: kubernetes-kubectl
    dest: kubernetes/bin/kubectl
    version: "{{kube_version}}"
    sha256: "{{kubectl_checksum}}"
    source_url: "{{ kubectl_download_url }}"
    url: "{{ kubectl_download_url }}"
    owner: "kube"
    mode: "0755"

  - name: kubernetes-apiserver
    dest: kubernetes/bin/kube-apiserver
    version: "{{kube_version}}"
    sha256: "{{kube_apiserver_checksum}}"
    source_url: "{{ apiserver_download_url }}"
    url: "{{ apiserver_download_url }}"
    owner: "kube"
    mode: "0755"
